# Generated by Django 5.2.10 on 2026-01-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='Formação Acadêmica'),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Experiência Profissional'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Idiomas'),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, help_text='Liste suas habilidades separadas por vírgula', null=True, verbose_name='Habilidades e Competências'),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Resumo Profissional'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
