# Generated by Django 5.2.10 on 2026-01-31 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_resume_education_resume_experience_resume_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título da Vaga')),
                ('company', models.CharField(max_length=200, verbose_name='Empresa')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('requirements', models.TextField(verbose_name='Requisitos')),
                ('location', models.CharField(max_length=100, verbose_name='Localização')),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Faixa Salarial')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicants', models.ManyToManyField(blank=True, related_name='applied_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
