# Generated by Django 6.0.4 on 2026-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_remove_job_applicants_job_created_by_job_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-similarity_score']},
        ),
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da entrevista'),
        ),
        migrations.AddField(
            model_name='application',
            name='recruiter_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas internas do recrutador'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Candidatura'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('pre_selected', 'Pré-seleccionado'), ('rejected', 'Rejeitado'), ('interview_scheduled', 'Entrevista Agendada')], default='pending', max_length=30),
        ),
    ]
