# Generated by Django 6.0.4 on 2026-05-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='availability_responded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_availability_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_unavailability_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='allow_candidate_unavailability',
            field=models.BooleanField(default=False, verbose_name='Permitir indicação de indisponibilidade'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email_primary',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto principal'),
        ),
        migrations.AddField(
            model_name='job',
            name='contact_email_secondary',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de contacto secundário'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('pre_selected', 'Pré-seleccionado'), ('rejected', 'Rejeitado'), ('interview_scheduled', 'Entrevista Agendada'), ('withdrawn', 'Candidatura Retirada')], default='pending', max_length=30),
        ),
    ]
