# Generated by Django 6.0.4 on 2026-05-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_application_availability_responded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_score_required',
            field=models.FloatField(default=0.0, verbose_name='Score mínimo para triagem automática'),
        ),
    ]
