# Generated by Django 6.0.4 on 2026-06-07 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recruiter_approved',
            field=models.BooleanField(default=True, verbose_name='Recrutador aprovado'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('export_csv', 'Exportação CSV'), ('status_change', 'Alteração de Estado de Candidatura'), ('job_toggle', 'Activação/Desactivação de Vaga'), ('resume_delete', 'Remoção de Currículo')], max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registo de Auditoria',
                'verbose_name_plural': 'Registos de Auditoria',
                'ordering': ['-timestamp'],
            },
        ),
    ]
