# Generated by Django 6.0.4 on 2026-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_security_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='awaiting_score',
            field=models.BooleanField(default=False),
        ),
    ]
