# Generated by Django 6.0.4 on 2026-06-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_awaiting_score_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='applications/', verbose_name='CV específico'),
        ),
        migrations.AddField(
            model_name='application',
            name='cv_parsed_text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto extraído do CV específico'),
        ),
    ]
