"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)
# Reading .env file
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-CHANGE-ME-before-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default=False)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "axes",
    "recruitment",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "axes.middleware.AxesMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "recruitment.context_processors.unread_notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import socket

_DB_HOST = env('DB_HOST', default='localhost')
_DB_PORT = env.int('DB_PORT', default=5432)


def _postgres_reachable(host, port, timeout=0.75):
    """Verificação leve (apenas TCP) - não valida credenciais, só se há algo a ouvir na porta."""
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except OSError:
        return False


# DB_ENGINE explícito no .env tem sempre prioridade (ex: forçar sqlite mesmo com Postgres a correr).
# Sem essa variável, detecta automaticamente: usa PostgreSQL se estiver acessível,
# caso contrário cai para SQLite - permite correr `manage.py runserver`/`test` num computador
# sem PostgreSQL instalado, sem exigir configuração manual.
DB_ENGINE = env('DB_ENGINE', default=None)
if not DB_ENGINE:
    if _postgres_reachable(_DB_HOST, _DB_PORT):
        DB_ENGINE = 'django.db.backends.postgresql'
    else:
        DB_ENGINE = 'django.db.backends.sqlite3'
        print(
            f"[KUBUKA] PostgreSQL nao encontrado em {_DB_HOST}:{_DB_PORT} - "
            f"a usar SQLite em '{BASE_DIR / 'db.sqlite3'}' (defina DB_ENGINE no .env para forcar)."
        )

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / env('DB_NAME', default='db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME':     env('DB_NAME',     default='kubuka_db'),
            'USER':     env('DB_USER',     default='kubuka_user'),
            'PASSWORD': env('DB_PASSWORD', default='kubuka_pass'),
            'HOST':     env('DB_HOST',     default='localhost'),
            'PORT':     env('DB_PORT',     default='5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "pt-pt"

TIME_ZONE = "Africa/Luanda"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise: serve estáticos comprimidos directamente pelo Django/gunicorn em
# produção, sem depender de um servidor web separado (nginx) só para isso.
# Em desenvolvimento (DEBUG=True) mantém-se o storage padrão do Django, para não
# exigir `collectstatic` antes de correr `runserver`.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage" if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'recruitment.User'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'recruitment.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'login'

# Email
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='KUBUKA <noreply@kubuka.ao>')

N8N_WEBHOOK_URL = env('N8N_WEBHOOK_URL', default='')
N8N_SECRET_TOKEN = env('N8N_SECRET_TOKEN', default='')
CALLBACK_SECRET = env('CALLBACK_SECRET', default='')

# n8n + Ollama
N8N_WEBHOOK_CV_URL = env('N8N_WEBHOOK_CV_URL', default='http://127.0.0.1:5678/webhook/cv-analysis')
N8N_WEBHOOK_SCORE_URL = env('N8N_WEBHOOK_SCORE_URL', default='http://127.0.0.1:5678/webhook/job-scoring')
N8N_CALLBACK_SECRET = env('N8N_CALLBACK_SECRET', default='')
DJANGO_BASE_URL = env('DJANGO_BASE_URL', default='http://127.0.0.1:8000')

# ---------------------------------------------------------------------------
# Limites de upload
# ---------------------------------------------------------------------------
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5 MB em memória
DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024   # 6 MB total por pedido

# ---------------------------------------------------------------------------
# Cabeçalhos de segurança HTTP
# ---------------------------------------------------------------------------
SECURE_CONTENT_TYPE_NOSNIFF = True    # X-Content-Type-Options: nosniff
SECURE_BROWSER_XSS_FILTER = True      # X-XSS-Protection (browsers antigos)
X_FRAME_OPTIONS = 'DENY'              # Proíbe iframes (clickjacking)

# Reforço de HTTPS/cookies: activado automaticamente sempre que DEBUG=False,
# sem exigir alterações manuais a este ficheiro antes de um deploy. Cada um
# pode ser desligado individualmente via .env (ex: 1º deploy ainda sem HTTPS).
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=not DEBUG)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=not DEBUG)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=not DEBUG)

# Necessário quando o Django corre atrás de um proxy/load balancer que termina o
# TLS (Render, Railway, nginx) - sem isto, SECURE_SSL_REDIRECT causa loop de redirect.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Domínios confiáveis para POST com CSRF em produção (ex: https://kubuka.ao).
# Vazio por omissão - não afecta o desenvolvimento local.
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[])

# ---------------------------------------------------------------------------
# django-axes - protecção contra força bruta no login
# ---------------------------------------------------------------------------
AXES_FAILURE_LIMIT = 5          # Bloquear após 5 tentativas falhadas
AXES_COOLOFF_TIME = 1           # Cooldown de 1 hora
AXES_RESET_ON_SUCCESS = True    # Reinicia contador após login bem-sucedido
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# ---------------------------------------------------------------------------
# Django REST Framework - throttling global
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/hour',
        'user': '200/hour',
    },
}

# ---------------------------------------------------------------------------
# Logging - consola sempre; ficheiro rotativo em logs/kubuka.log
# ---------------------------------------------------------------------------
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'kubuka.log',
            'maxBytes': 5 * 1024 * 1024,   # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'recruitment': {
            'handlers': ['console', 'file'],
            'level': env('DJANGO_LOG_LEVEL', default='INFO'),
            'propagate': False,
        },
    },
}
